### 
# Create new Short URL 
POST http://localhost:8080/api/createUrl
Content-Type: application/json

{
  "targetUrl": "https://www.coingecko.com"
}

###
# Get Target URL by Short URL
GET http://localhost:8080/r/XZNaxizAcX

###
# Get Usage Report by Short Code
GET http://localhost:8080/api/report/short-code/?shortCode=XZNaxizAcX


